import { cn } from '@repo/utils';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';

import './globals.css';
import { Sidebar } from '@components/Sidebar';

const inter = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="gs">
      <body className={cn(inter.className, 'antialiased flex bg-[#f1f1f7]')}>
        <Sidebar />
        <div className="flex flex-col px-12 py-16  min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
